# Generated by Django 6.0.5 on 2026-06-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('property_view', 'Property View'), ('search', 'Search'), ('favorite_add', 'Favorite Add'), ('booking_created', 'Booking Created'), ('contact_agent', 'Contact Agent'), ('user_signup', 'User Signup'), ('session_start', 'Session Start')], max_length=50)),
                ('metadata', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
