# Generated by Django 6.0.5 on 2026-06-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('rent', 'For Rent'), ('sale', 'For Sale'), ('bnb', 'BnB / Per Night')], max_length=10),
        ),
    ]
